/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as BoardIdRouteImport } from './routes/board/$id';
import { Route as BoardsRouteImport } from './routes/boards';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ResourcesActivityActivityIdRouteImport } from './routes/resources/activity/$activityId';
import { Route as ResourcesActivityCreateRouteImport } from './routes/resources/activity/create';
import { Route as ResourcesActivityGetRouteImport } from './routes/resources/activity/get';
import { Route as ResourcesBoardsBoardIdRouteImport } from './routes/resources/boards/$boardId';
import { Route as ResourcesBoardsCreateRouteImport } from './routes/resources/boards/create';
import { Route as ResourcesBoardsGetRouteImport } from './routes/resources/boards/get';
import { Route as ResourcesCardsCardIdRouteImport } from './routes/resources/cards/$cardId';
import { Route as ResourcesCardsCreateRouteImport } from './routes/resources/cards/create';
import { Route as ResourcesCardsGetRouteImport } from './routes/resources/cards/get';
import { Route as ResourcesChecklistItemsItemIdRouteImport } from './routes/resources/checklist-items/$itemId';
import { Route as ResourcesChecklistItemsCreateRouteImport } from './routes/resources/checklist-items/create';
import { Route as ResourcesChecklistItemsGetRouteImport } from './routes/resources/checklist-items/get';
import { Route as ResourcesChecklistsCreateRouteImport } from './routes/resources/checklists/create';
import { Route as ResourcesChecklistsDeleteRouteImport } from './routes/resources/checklists/delete';
import { Route as ResourcesChecklistsGetRouteImport } from './routes/resources/checklists/get';
import { Route as ResourcesListsListIdRouteImport } from './routes/resources/lists/$listId';
import { Route as ResourcesListsCreateRouteImport } from './routes/resources/lists/create';
import { Route as ResourcesListsGetRouteImport } from './routes/resources/lists/get';
import { Route as ResourcesProfilesGetRouteImport } from './routes/resources/profiles/get';
import { Route as ResourcesRegisterRouteImport } from './routes/resources/register';
import { Route as ResourcesSigninRouteImport } from './routes/resources/signin';
import { Route as SigninRouteImport } from './routes/signin';

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any);
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesSigninRoute = ResourcesSigninRouteImport.update({
  id: '/resources/signin',
  path: '/resources/signin',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesRegisterRoute = ResourcesRegisterRouteImport.update({
  id: '/resources/register',
  path: '/resources/register',
  getParentRoute: () => rootRouteImport,
} as any);
const BoardIdRoute = BoardIdRouteImport.update({
  id: '/board/$id',
  path: '/board/$id',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesProfilesGetRoute = ResourcesProfilesGetRouteImport.update({
  id: '/resources/profiles/get',
  path: '/resources/profiles/get',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesListsGetRoute = ResourcesListsGetRouteImport.update({
  id: '/resources/lists/get',
  path: '/resources/lists/get',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesListsCreateRoute = ResourcesListsCreateRouteImport.update({
  id: '/resources/lists/create',
  path: '/resources/lists/create',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesListsListIdRoute = ResourcesListsListIdRouteImport.update({
  id: '/resources/lists/$listId',
  path: '/resources/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesChecklistsGetRoute = ResourcesChecklistsGetRouteImport.update({
  id: '/resources/checklists/get',
  path: '/resources/checklists/get',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesChecklistsDeleteRoute =
  ResourcesChecklistsDeleteRouteImport.update({
    id: '/resources/checklists/delete',
    path: '/resources/checklists/delete',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResourcesChecklistsCreateRoute =
  ResourcesChecklistsCreateRouteImport.update({
    id: '/resources/checklists/create',
    path: '/resources/checklists/create',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResourcesChecklistItemsGetRoute =
  ResourcesChecklistItemsGetRouteImport.update({
    id: '/resources/checklist-items/get',
    path: '/resources/checklist-items/get',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResourcesChecklistItemsCreateRoute =
  ResourcesChecklistItemsCreateRouteImport.update({
    id: '/resources/checklist-items/create',
    path: '/resources/checklist-items/create',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResourcesChecklistItemsItemIdRoute =
  ResourcesChecklistItemsItemIdRouteImport.update({
    id: '/resources/checklist-items/$itemId',
    path: '/resources/checklist-items/$itemId',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResourcesCardsGetRoute = ResourcesCardsGetRouteImport.update({
  id: '/resources/cards/get',
  path: '/resources/cards/get',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesCardsCreateRoute = ResourcesCardsCreateRouteImport.update({
  id: '/resources/cards/create',
  path: '/resources/cards/create',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesCardsCardIdRoute = ResourcesCardsCardIdRouteImport.update({
  id: '/resources/cards/$cardId',
  path: '/resources/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesBoardsGetRoute = ResourcesBoardsGetRouteImport.update({
  id: '/resources/boards/get',
  path: '/resources/boards/get',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesBoardsCreateRoute = ResourcesBoardsCreateRouteImport.update({
  id: '/resources/boards/create',
  path: '/resources/boards/create',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesBoardsBoardIdRoute = ResourcesBoardsBoardIdRouteImport.update({
  id: '/resources/boards/$boardId',
  path: '/resources/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesActivityGetRoute = ResourcesActivityGetRouteImport.update({
  id: '/resources/activity/get',
  path: '/resources/activity/get',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesActivityCreateRoute = ResourcesActivityCreateRouteImport.update({
  id: '/resources/activity/create',
  path: '/resources/activity/create',
  getParentRoute: () => rootRouteImport,
} as any);
const ResourcesActivityActivityIdRoute =
  ResourcesActivityActivityIdRouteImport.update({
    id: '/resources/activity/$activityId',
    path: '/resources/activity/$activityId',
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/boards': typeof BoardsRoute;
  '/signin': typeof SigninRoute;
  '/board/$id': typeof BoardIdRoute;
  '/resources/register': typeof ResourcesRegisterRoute;
  '/resources/signin': typeof ResourcesSigninRoute;
  '/resources/activity/$activityId': typeof ResourcesActivityActivityIdRoute;
  '/resources/activity/create': typeof ResourcesActivityCreateRoute;
  '/resources/activity/get': typeof ResourcesActivityGetRoute;
  '/resources/boards/$boardId': typeof ResourcesBoardsBoardIdRoute;
  '/resources/boards/create': typeof ResourcesBoardsCreateRoute;
  '/resources/boards/get': typeof ResourcesBoardsGetRoute;
  '/resources/cards/$cardId': typeof ResourcesCardsCardIdRoute;
  '/resources/cards/create': typeof ResourcesCardsCreateRoute;
  '/resources/cards/get': typeof ResourcesCardsGetRoute;
  '/resources/checklist-items/$itemId': typeof ResourcesChecklistItemsItemIdRoute;
  '/resources/checklist-items/create': typeof ResourcesChecklistItemsCreateRoute;
  '/resources/checklist-items/get': typeof ResourcesChecklistItemsGetRoute;
  '/resources/checklists/create': typeof ResourcesChecklistsCreateRoute;
  '/resources/checklists/delete': typeof ResourcesChecklistsDeleteRoute;
  '/resources/checklists/get': typeof ResourcesChecklistsGetRoute;
  '/resources/lists/$listId': typeof ResourcesListsListIdRoute;
  '/resources/lists/create': typeof ResourcesListsCreateRoute;
  '/resources/lists/get': typeof ResourcesListsGetRoute;
  '/resources/profiles/get': typeof ResourcesProfilesGetRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/boards': typeof BoardsRoute;
  '/signin': typeof SigninRoute;
  '/board/$id': typeof BoardIdRoute;
  '/resources/register': typeof ResourcesRegisterRoute;
  '/resources/signin': typeof ResourcesSigninRoute;
  '/resources/activity/$activityId': typeof ResourcesActivityActivityIdRoute;
  '/resources/activity/create': typeof ResourcesActivityCreateRoute;
  '/resources/activity/get': typeof ResourcesActivityGetRoute;
  '/resources/boards/$boardId': typeof ResourcesBoardsBoardIdRoute;
  '/resources/boards/create': typeof ResourcesBoardsCreateRoute;
  '/resources/boards/get': typeof ResourcesBoardsGetRoute;
  '/resources/cards/$cardId': typeof ResourcesCardsCardIdRoute;
  '/resources/cards/create': typeof ResourcesCardsCreateRoute;
  '/resources/cards/get': typeof ResourcesCardsGetRoute;
  '/resources/checklist-items/$itemId': typeof ResourcesChecklistItemsItemIdRoute;
  '/resources/checklist-items/create': typeof ResourcesChecklistItemsCreateRoute;
  '/resources/checklist-items/get': typeof ResourcesChecklistItemsGetRoute;
  '/resources/checklists/create': typeof ResourcesChecklistsCreateRoute;
  '/resources/checklists/delete': typeof ResourcesChecklistsDeleteRoute;
  '/resources/checklists/get': typeof ResourcesChecklistsGetRoute;
  '/resources/lists/$listId': typeof ResourcesListsListIdRoute;
  '/resources/lists/create': typeof ResourcesListsCreateRoute;
  '/resources/lists/get': typeof ResourcesListsGetRoute;
  '/resources/profiles/get': typeof ResourcesProfilesGetRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/boards': typeof BoardsRoute;
  '/signin': typeof SigninRoute;
  '/board/$id': typeof BoardIdRoute;
  '/resources/register': typeof ResourcesRegisterRoute;
  '/resources/signin': typeof ResourcesSigninRoute;
  '/resources/activity/$activityId': typeof ResourcesActivityActivityIdRoute;
  '/resources/activity/create': typeof ResourcesActivityCreateRoute;
  '/resources/activity/get': typeof ResourcesActivityGetRoute;
  '/resources/boards/$boardId': typeof ResourcesBoardsBoardIdRoute;
  '/resources/boards/create': typeof ResourcesBoardsCreateRoute;
  '/resources/boards/get': typeof ResourcesBoardsGetRoute;
  '/resources/cards/$cardId': typeof ResourcesCardsCardIdRoute;
  '/resources/cards/create': typeof ResourcesCardsCreateRoute;
  '/resources/cards/get': typeof ResourcesCardsGetRoute;
  '/resources/checklist-items/$itemId': typeof ResourcesChecklistItemsItemIdRoute;
  '/resources/checklist-items/create': typeof ResourcesChecklistItemsCreateRoute;
  '/resources/checklist-items/get': typeof ResourcesChecklistItemsGetRoute;
  '/resources/checklists/create': typeof ResourcesChecklistsCreateRoute;
  '/resources/checklists/delete': typeof ResourcesChecklistsDeleteRoute;
  '/resources/checklists/get': typeof ResourcesChecklistsGetRoute;
  '/resources/lists/$listId': typeof ResourcesListsListIdRoute;
  '/resources/lists/create': typeof ResourcesListsCreateRoute;
  '/resources/lists/get': typeof ResourcesListsGetRoute;
  '/resources/profiles/get': typeof ResourcesProfilesGetRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/boards'
    | '/signin'
    | '/board/$id'
    | '/resources/register'
    | '/resources/signin'
    | '/resources/activity/$activityId'
    | '/resources/activity/create'
    | '/resources/activity/get'
    | '/resources/boards/$boardId'
    | '/resources/boards/create'
    | '/resources/boards/get'
    | '/resources/cards/$cardId'
    | '/resources/cards/create'
    | '/resources/cards/get'
    | '/resources/checklist-items/$itemId'
    | '/resources/checklist-items/create'
    | '/resources/checklist-items/get'
    | '/resources/checklists/create'
    | '/resources/checklists/delete'
    | '/resources/checklists/get'
    | '/resources/lists/$listId'
    | '/resources/lists/create'
    | '/resources/lists/get'
    | '/resources/profiles/get';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/boards'
    | '/signin'
    | '/board/$id'
    | '/resources/register'
    | '/resources/signin'
    | '/resources/activity/$activityId'
    | '/resources/activity/create'
    | '/resources/activity/get'
    | '/resources/boards/$boardId'
    | '/resources/boards/create'
    | '/resources/boards/get'
    | '/resources/cards/$cardId'
    | '/resources/cards/create'
    | '/resources/cards/get'
    | '/resources/checklist-items/$itemId'
    | '/resources/checklist-items/create'
    | '/resources/checklist-items/get'
    | '/resources/checklists/create'
    | '/resources/checklists/delete'
    | '/resources/checklists/get'
    | '/resources/lists/$listId'
    | '/resources/lists/create'
    | '/resources/lists/get'
    | '/resources/profiles/get';
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/signin'
    | '/board/$id'
    | '/resources/register'
    | '/resources/signin'
    | '/resources/activity/$activityId'
    | '/resources/activity/create'
    | '/resources/activity/get'
    | '/resources/boards/$boardId'
    | '/resources/boards/create'
    | '/resources/boards/get'
    | '/resources/cards/$cardId'
    | '/resources/cards/create'
    | '/resources/cards/get'
    | '/resources/checklist-items/$itemId'
    | '/resources/checklist-items/create'
    | '/resources/checklist-items/get'
    | '/resources/checklists/create'
    | '/resources/checklists/delete'
    | '/resources/checklists/get'
    | '/resources/lists/$listId'
    | '/resources/lists/create'
    | '/resources/lists/get'
    | '/resources/profiles/get';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BoardsRoute: typeof BoardsRoute;
  SigninRoute: typeof SigninRoute;
  BoardIdRoute: typeof BoardIdRoute;
  ResourcesRegisterRoute: typeof ResourcesRegisterRoute;
  ResourcesSigninRoute: typeof ResourcesSigninRoute;
  ResourcesActivityActivityIdRoute: typeof ResourcesActivityActivityIdRoute;
  ResourcesActivityCreateRoute: typeof ResourcesActivityCreateRoute;
  ResourcesActivityGetRoute: typeof ResourcesActivityGetRoute;
  ResourcesBoardsBoardIdRoute: typeof ResourcesBoardsBoardIdRoute;
  ResourcesBoardsCreateRoute: typeof ResourcesBoardsCreateRoute;
  ResourcesBoardsGetRoute: typeof ResourcesBoardsGetRoute;
  ResourcesCardsCardIdRoute: typeof ResourcesCardsCardIdRoute;
  ResourcesCardsCreateRoute: typeof ResourcesCardsCreateRoute;
  ResourcesCardsGetRoute: typeof ResourcesCardsGetRoute;
  ResourcesChecklistItemsItemIdRoute: typeof ResourcesChecklistItemsItemIdRoute;
  ResourcesChecklistItemsCreateRoute: typeof ResourcesChecklistItemsCreateRoute;
  ResourcesChecklistItemsGetRoute: typeof ResourcesChecklistItemsGetRoute;
  ResourcesChecklistsCreateRoute: typeof ResourcesChecklistsCreateRoute;
  ResourcesChecklistsDeleteRoute: typeof ResourcesChecklistsDeleteRoute;
  ResourcesChecklistsGetRoute: typeof ResourcesChecklistsGetRoute;
  ResourcesListsListIdRoute: typeof ResourcesListsListIdRoute;
  ResourcesListsCreateRoute: typeof ResourcesListsCreateRoute;
  ResourcesListsGetRoute: typeof ResourcesListsGetRoute;
  ResourcesProfilesGetRoute: typeof ResourcesProfilesGetRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin';
      path: '/signin';
      fullPath: '/signin';
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/boards': {
      id: '/boards';
      path: '/boards';
      fullPath: '/boards';
      preLoaderRoute: typeof BoardsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/signin': {
      id: '/resources/signin';
      path: '/resources/signin';
      fullPath: '/resources/signin';
      preLoaderRoute: typeof ResourcesSigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/register': {
      id: '/resources/register';
      path: '/resources/register';
      fullPath: '/resources/register';
      preLoaderRoute: typeof ResourcesRegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/board/$id': {
      id: '/board/$id';
      path: '/board/$id';
      fullPath: '/board/$id';
      preLoaderRoute: typeof BoardIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/profiles/get': {
      id: '/resources/profiles/get';
      path: '/resources/profiles/get';
      fullPath: '/resources/profiles/get';
      preLoaderRoute: typeof ResourcesProfilesGetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/lists/get': {
      id: '/resources/lists/get';
      path: '/resources/lists/get';
      fullPath: '/resources/lists/get';
      preLoaderRoute: typeof ResourcesListsGetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/lists/create': {
      id: '/resources/lists/create';
      path: '/resources/lists/create';
      fullPath: '/resources/lists/create';
      preLoaderRoute: typeof ResourcesListsCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/lists/$listId': {
      id: '/resources/lists/$listId';
      path: '/resources/lists/$listId';
      fullPath: '/resources/lists/$listId';
      preLoaderRoute: typeof ResourcesListsListIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/checklists/get': {
      id: '/resources/checklists/get';
      path: '/resources/checklists/get';
      fullPath: '/resources/checklists/get';
      preLoaderRoute: typeof ResourcesChecklistsGetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/checklists/delete': {
      id: '/resources/checklists/delete';
      path: '/resources/checklists/delete';
      fullPath: '/resources/checklists/delete';
      preLoaderRoute: typeof ResourcesChecklistsDeleteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/checklists/create': {
      id: '/resources/checklists/create';
      path: '/resources/checklists/create';
      fullPath: '/resources/checklists/create';
      preLoaderRoute: typeof ResourcesChecklistsCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/checklist-items/get': {
      id: '/resources/checklist-items/get';
      path: '/resources/checklist-items/get';
      fullPath: '/resources/checklist-items/get';
      preLoaderRoute: typeof ResourcesChecklistItemsGetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/checklist-items/create': {
      id: '/resources/checklist-items/create';
      path: '/resources/checklist-items/create';
      fullPath: '/resources/checklist-items/create';
      preLoaderRoute: typeof ResourcesChecklistItemsCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/checklist-items/$itemId': {
      id: '/resources/checklist-items/$itemId';
      path: '/resources/checklist-items/$itemId';
      fullPath: '/resources/checklist-items/$itemId';
      preLoaderRoute: typeof ResourcesChecklistItemsItemIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/cards/get': {
      id: '/resources/cards/get';
      path: '/resources/cards/get';
      fullPath: '/resources/cards/get';
      preLoaderRoute: typeof ResourcesCardsGetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/cards/create': {
      id: '/resources/cards/create';
      path: '/resources/cards/create';
      fullPath: '/resources/cards/create';
      preLoaderRoute: typeof ResourcesCardsCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/cards/$cardId': {
      id: '/resources/cards/$cardId';
      path: '/resources/cards/$cardId';
      fullPath: '/resources/cards/$cardId';
      preLoaderRoute: typeof ResourcesCardsCardIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/boards/get': {
      id: '/resources/boards/get';
      path: '/resources/boards/get';
      fullPath: '/resources/boards/get';
      preLoaderRoute: typeof ResourcesBoardsGetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/boards/create': {
      id: '/resources/boards/create';
      path: '/resources/boards/create';
      fullPath: '/resources/boards/create';
      preLoaderRoute: typeof ResourcesBoardsCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/boards/$boardId': {
      id: '/resources/boards/$boardId';
      path: '/resources/boards/$boardId';
      fullPath: '/resources/boards/$boardId';
      preLoaderRoute: typeof ResourcesBoardsBoardIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/activity/get': {
      id: '/resources/activity/get';
      path: '/resources/activity/get';
      fullPath: '/resources/activity/get';
      preLoaderRoute: typeof ResourcesActivityGetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/activity/create': {
      id: '/resources/activity/create';
      path: '/resources/activity/create';
      fullPath: '/resources/activity/create';
      preLoaderRoute: typeof ResourcesActivityCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/resources/activity/$activityId': {
      id: '/resources/activity/$activityId';
      path: '/resources/activity/$activityId';
      fullPath: '/resources/activity/$activityId';
      preLoaderRoute: typeof ResourcesActivityActivityIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  SigninRoute: SigninRoute,
  BoardIdRoute: BoardIdRoute,
  ResourcesRegisterRoute: ResourcesRegisterRoute,
  ResourcesSigninRoute: ResourcesSigninRoute,
  ResourcesActivityActivityIdRoute: ResourcesActivityActivityIdRoute,
  ResourcesActivityCreateRoute: ResourcesActivityCreateRoute,
  ResourcesActivityGetRoute: ResourcesActivityGetRoute,
  ResourcesBoardsBoardIdRoute: ResourcesBoardsBoardIdRoute,
  ResourcesBoardsCreateRoute: ResourcesBoardsCreateRoute,
  ResourcesBoardsGetRoute: ResourcesBoardsGetRoute,
  ResourcesCardsCardIdRoute: ResourcesCardsCardIdRoute,
  ResourcesCardsCreateRoute: ResourcesCardsCreateRoute,
  ResourcesCardsGetRoute: ResourcesCardsGetRoute,
  ResourcesChecklistItemsItemIdRoute: ResourcesChecklistItemsItemIdRoute,
  ResourcesChecklistItemsCreateRoute: ResourcesChecklistItemsCreateRoute,
  ResourcesChecklistItemsGetRoute: ResourcesChecklistItemsGetRoute,
  ResourcesChecklistsCreateRoute: ResourcesChecklistsCreateRoute,
  ResourcesChecklistsDeleteRoute: ResourcesChecklistsDeleteRoute,
  ResourcesChecklistsGetRoute: ResourcesChecklistsGetRoute,
  ResourcesListsListIdRoute: ResourcesListsListIdRoute,
  ResourcesListsCreateRoute: ResourcesListsCreateRoute,
  ResourcesListsGetRoute: ResourcesListsGetRoute,
  ResourcesProfilesGetRoute: ResourcesProfilesGetRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
