/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardCardIdRouteImport } from './routes/card.$cardId'
import { Route as BoardIdRouteImport } from './routes/board.$id'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as BoardIdCardCardIdRouteImport } from './routes/board.$id.card.$cardId'

const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardCardIdRoute = CardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIdRoute = BoardIdRouteImport.update({
  id: '/board/$id',
  path: '/board/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIdCardCardIdRoute = BoardIdCardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => BoardIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/board/$id': typeof BoardIdRouteWithChildren
  '/card/$cardId': typeof CardCardIdRoute
  '/board/$id/card/$cardId': typeof BoardIdCardCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/board/$id': typeof BoardIdRouteWithChildren
  '/card/$cardId': typeof CardCardIdRoute
  '/board/$id/card/$cardId': typeof BoardIdCardCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/board/$id': typeof BoardIdRouteWithChildren
  '/card/$cardId': typeof CardCardIdRoute
  '/board/$id/card/$cardId': typeof BoardIdCardCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/auth/sign-in'
    | '/board/$id'
    | '/card/$cardId'
    | '/board/$id/card/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/auth/sign-in'
    | '/board/$id'
    | '/card/$cardId'
    | '/board/$id/card/$cardId'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/auth/sign-in'
    | '/board/$id'
    | '/card/$cardId'
    | '/board/$id/card/$cardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  AuthSignInRoute: typeof AuthSignInRoute
  BoardIdRoute: typeof BoardIdRouteWithChildren
  CardCardIdRoute: typeof CardCardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$cardId': {
      id: '/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/card/$cardId'
      preLoaderRoute: typeof CardCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$id': {
      id: '/board/$id'
      path: '/board/$id'
      fullPath: '/board/$id'
      preLoaderRoute: typeof BoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$id/card/$cardId': {
      id: '/board/$id/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/board/$id/card/$cardId'
      preLoaderRoute: typeof BoardIdCardCardIdRouteImport
      parentRoute: typeof BoardIdRoute
    }
  }
}

interface BoardIdRouteChildren {
  BoardIdCardCardIdRoute: typeof BoardIdCardCardIdRoute
}

const BoardIdRouteChildren: BoardIdRouteChildren = {
  BoardIdCardCardIdRoute: BoardIdCardCardIdRoute,
}

const BoardIdRouteWithChildren =
  BoardIdRoute._addFileChildren(BoardIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  AuthSignInRoute: AuthSignInRoute,
  BoardIdRoute: BoardIdRouteWithChildren,
  CardCardIdRoute: CardCardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
